// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qsti.ReciboOnline.Infra.Repositories.Base;

namespace Qsti.ReciboOnline.Infra.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Administrador");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataBloqueio");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime?>("DataDesbloqueio");

                    b.Property<DateTime>("DataUltimaMudancaStatus");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Motivo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Status");

                    b.Property<Guid?>("UsuarioBloqueioId");

                    b.Property<Guid?>("UsuarioDesbloqueioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioBloqueioId");

                    b.HasIndex("UsuarioDesbloqueioId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.PushNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("FuncionarioId");

                    b.Property<Guid?>("IdUsuario");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PushNotification");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Recibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ano")
                        .HasMaxLength(4);

                    b.Property<double>("BaseFGTS")
                        .HasMaxLength(20);

                    b.Property<double>("BaseINSS")
                        .HasMaxLength(20);

                    b.Property<double>("BaseIR")
                        .HasMaxLength(20);

                    b.Property<double>("BaseIRFerias")
                        .HasMaxLength(20);

                    b.Property<string>("CNPJ")
                        .HasMaxLength(14);

                    b.Property<string>("CentroCusto")
                        .HasMaxLength(25);

                    b.Property<string>("Cidade")
                        .HasMaxLength(20);

                    b.Property<int>("CodigoPd");

                    b.Property<string>("ContaCorrente")
                        .HasMaxLength(25);

                    b.Property<string>("DescricaoCodigoPD")
                        .HasMaxLength(50);

                    b.Property<string>("DescricaoTipo")
                        .HasMaxLength(20);

                    b.Property<double>("FGTSMes")
                        .HasMaxLength(20);

                    b.Property<string>("Funcao")
                        .HasMaxLength(40);

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50);

                    b.Property<string>("Matricula")
                        .HasMaxLength(10);

                    b.Property<string>("Mes")
                        .HasMaxLength(2);

                    b.Property<string>("Nome")
                        .HasMaxLength(40);

                    b.Property<int>("Numero");

                    b.Property<int>("OrdemTipo")
                        .HasMaxLength(20);

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(40);

                    b.Property<string>("Referencia")
                        .HasMaxLength(20);

                    b.Property<double>("SalarioBase")
                        .HasMaxLength(20);

                    b.Property<Guid?>("SolicitacaoId");

                    b.Property<bool>("Status");

                    b.Property<string>("TipoCodigo")
                        .HasMaxLength(1);

                    b.Property<int>("TipoFolha");

                    b.Property<double>("TotalDescontos")
                        .HasMaxLength(20);

                    b.Property<double>("TotalLiquido")
                        .HasMaxLength(20);

                    b.Property<double>("TotalProventos")
                        .HasMaxLength(20);

                    b.Property<string>("UF")
                        .HasMaxLength(2);

                    b.Property<double>("Valor")
                        .HasMaxLength(20);

                    b.Property<bool>("Visualizado");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("Recibo");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ano")
                        .HasMaxLength(4);

                    b.Property<string>("Matricula");

                    b.Property<string>("Mes")
                        .HasMaxLength(2);

                    b.Property<int>("Status");

                    b.Property<int>("TipoFolha");

                    b.Property<Guid?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Solicitacao");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime>("DataUltimaMudancaStatus");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<int>("Status");

                    b.Property<Guid?>("UsuarioUltimaAlteracaoId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioUltimaAlteracaoId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("Qsti.ReciboOnline.Domain.Entities.Usuario", "UsuarioBloqueio")
                        .WithMany()
                        .HasForeignKey("UsuarioBloqueioId");

                    b.HasOne("Qsti.ReciboOnline.Domain.Entities.Usuario", "UsuarioDesbloqueio")
                        .WithMany()
                        .HasForeignKey("UsuarioDesbloqueioId");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.PushNotification", b =>
                {
                    b.HasOne("Qsti.ReciboOnline.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("Qsti.ReciboOnline.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Recibo", b =>
                {
                    b.HasOne("Qsti.ReciboOnline.Domain.Entities.Solicitacao", "Solicitacao")
                        .WithMany()
                        .HasForeignKey("SolicitacaoId");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Solicitacao", b =>
                {
                    b.HasOne("Qsti.ReciboOnline.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Qsti.ReciboOnline.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Qsti.ReciboOnline.Domain.Entities.Usuario", "UsuarioUltimaAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioUltimaAlteracaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
